server:
  port: 8085

grpc:
  server:
    port: 6565

axon:
  axonserver:
    enabled: true
    component-name: user-service
    servers: axonserver.axon.svc.cluster.local:8124

spring:
  application:
    name: UserService
