server:
  port: 8085

grpc:
  server:
    port: 6565

axon:
  axonserver:
    enabled: true
    component-name: order-service
    servers: ${AXONSERVER_URL}

spring:
  application:
    name: UserService
