name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
    - uses: actions/checkout@v4
    - name: set short_sha
      id: vars
      shell: bash
      run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
    - name: Render setting.xml
      env: 
        GH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: envsubst < .github/ci/settings.xml.template > settings.xml
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: docker build image to dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max

        secrets: |
          maven_settings=settings.xml
        push: true
        tags: hardingtrutran/userservice:${{ steps.vars.outputs.short_sha }}

    - name: Clean up rendered secret file
      if: always()
      run: rm -f settings.xml
  
  update-k8s:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install yd
        uses: mikefarah/yq@v4.44.3
      - name: update kubernetes mainfest
        run: |
          FILE=./k8s/userservice-pod.yml
          yq -i '.spec.template.spec.containers[0].image = "hardingtrutran/userservice:${{ needs.build.outputs.short_sha }}"' "$FILE"
      - name: commit deployment product service file change
        run: |
          git config --global user.email "vantruit@gmail.com"
          git config --global user.name "vantru"
          git add k8s/userservice-pod.yml
          git commit -m "change tag sha"
          git push origin main
