name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  call-build:
    uses: vantru/shared-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: userservice
      context: .
    secrets: inherit
  
  update-k8s:
      needs: call-build
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: install yq
          run: |
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq

        - name: update kubernetes manifest
          run: |
            FILE=./k8s/userservice-pod.yml
            yq -i '.spec.template.spec.containers[0].image = "${{ secrets.DOCKER_USERNAME }}/userservice:${{ needs.call-build.outputs.short_sha }}"' "$FILE"

        - name: commit deployment userservice file change
          run: |
            git config --global user.email "vantruit@gmail.com"
            git config --global user.name "vantru"
            git add k8s/userservice-pod.yml
            git commit -m "change tag sha"
            git push origin main
